#!/usr/bin/env ruby

def main(action)
  Dir.chdir(File.expand_path("..", __dir__))

  # Local dev.
  if action == "serve"
    ENV['ALLOW_ARM_ONLY_REPORTS'] = '1'
    system RbConfig.ruby, "continuous_reporting/file_benchmark_data_into_raw.rb", "-d", "data"
    system RbConfig.ruby, "continuous_reporting/generate_and_upload_reports.rb"
  end

  exec RbConfig.ruby, "-rbundler/setup", "site/_framework/render.rb", action
end

unless ARGV.size == 1
  puts "Specify action of 'build' or 'serve'"
  exit 1
end

main(ARGV.first)
