source 'https://rubygems.org'

gem 'aws-sdk-ec2', '~> 1'

# We directly use the above but get warnings if the following aren't listed.
gem 'nokogiri'
gem 'base64'
gem 'ostruct'
gem 'logger'
gem 'fiddle'
