name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: yjit-metrics
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          path: yjit-metrics

      # - name: Checkout ruby-bench
      #   uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      #   with:
      #     repository: ruby/ruby-bench
      #     path: yjit-metrics/build/ruby-bench

      - uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd # v1.288.0
        with:
          bundler-cache: true
          working-directory: yjit-metrics

      - name: Setup CPU
        run: ./setup.sh cpu

      - name: Run tests
        run: bundle exec rake
        env:
          TEST_OPTS: "-v"
